"""Validate commit message format: [TAG] module: description.

Allowed tags: FIX IMP ADD REM REF REV MOV REL MERGE CLA I18N PERF
Merge commits are allowed as-is.

Usage (called by pre-commit commit-msg hook):
    python scripts/check_commit_msg.py .git/COMMIT_EDITMSG
"""

import re
import sys

ALLOWED_TAGS = {
    "FIX",
    "IMP",
    "ADD",
    "REM",
    "REF",
    "REV",
    "MOV",
    "REL",
    "MERGE",
    "CLA",
    "I18N",
    "PERF",
}

PATTERN = re.compile(r"^\[(" + "|".join(ALLOWED_TAGS) + r")\] .+: .+")


def main():
    msg_file = sys.argv[1]
    with open(msg_file) as f:
        first_line = f.readline().strip()

    # Allow merge commits generated by git
    if first_line.startswith("Merge "):
        return 0

    if PATTERN.match(first_line):
        return 0

    tags = " ".join(sorted(ALLOWED_TAGS))
    print(f"Bad commit message format: {first_line!r}")
    print()
    print("Expected: [TAG] module: short description")
    print(f"Allowed tags: {tags}")
    print()
    print("Examples:")
    print("  [FIX] core/auth: handle expired tokens gracefully")
    print("  [ADD] plugins/telegram: webhook support for group chats")
    print("  [REF] ui/templates: extract shared sidebar component")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
